name: inventory
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
   flutter:
     sdk: flutter
   cupertino_icons: ^1.0.8
   equatable: ^2.0.7
   firebase_core: ^4.2.1
   firebase_auth: ^6.1.2
   cloud_firestore: ^6.1.0
   dartz: ^0.10.1
   provider: ^6.1.1
   http: ^1.2.1
   image_picker: ^1.1.2
   fl_chart: ^0.66.0
   pdf: ^3.11.3
   printing: ^5.14.2
   path_provider: ^2.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - lib/assets/background2.png
    - lib/assets/background.png
    - lib/assets/logo.png
